builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
#      - '386'
#      - arm
#      - arm64
#    ignore:
#      - goos: darwin
#        goarch: '386'
    binary: '{{ .ProjectName }}_v{{ .Version }}'
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - id: sigs
    artifacts: checksum
    args:
      # if you are using this is a GitHub action or some other automated pipeline, you
      # need to pass the batch flag to indicate its not interactive.
      - '--batch'
      - '--local-user'
      - '{{ .Env.GPG_FINGERPRINT }}' # set this environment variable for your signing key
      - '--output'
      - '${signature}'
      - '--detach-sign'
      - '${artifact}'
release:
  # Explicit set the repo to release from. Default is origin.
  github:
    owner: mpntech
    name: terraform-provider-okta
  # Visit your project's GitHub Releases page to publish this release.
  draft: true
changelog:
  skip: true
publishers:
- name: tfcloud checksum
  env:
    - TFE_TOKEN={{ .Env.TFE_TOKEN }}
    - TFE_ORG=marcopolonetwork
    - TFE_NAMESPACE=marcopolonetwork
    - TFE_KEYID={{ .Env.TFE_KEYID }}
  cmd: /usr/local/bin/gorelease-publisher-tfcloud provider private {{ abs .ArtifactPath }}
  checksum: true
  ids:
    - checksum
- name: tfcloud sigs
  env:
    - TFE_TOKEN={{ .Env.TFE_TOKEN }}
    - TFE_ORG=marcopolonetwork
    - TFE_NAMESPACE=marcopolonetwork
    - TFE_KEYID={{ .Env.TFE_KEYID }}
  cmd: /usr/local/bin/gorelease-publisher-tfcloud provider private {{ abs .ArtifactPath }}
  signature: true
  ids:
    - sigs
- name: tfcloud
  env:
    - TFE_TOKEN={{ .Env.TFE_TOKEN }}
    - TFE_ORG=marcopolonetwork
    - TFE_NAMESPACE=marcopolonetwork
    - TFE_KEYID={{ .Env.TFE_KEYID }}
  cmd: /usr/local/bin/gorelease-publisher-tfcloud provider private {{ abs .ArtifactPath }}
